config/routes.rb
Usrcube::Application.routes.draw do
  resources :messages, only: [:new, :create]

  root  'static_pages#home'

  match '/apps',                  to: 'static_pages#apps',              via: 'get'
  match '/apps/houseLoan',        to: 'static_pages#houseLoan',         via: 'get'
  match '/apps/houseBuyRent',     to: 'static_pages#houseBuyRent',      via: 'get'
  match '/apps/loanPrepay',       to: 'static_pages#loanPrepay',        via: 'get'
  match '/apps/aprPaydayLoan',    to: 'static_pages#aprPaydayLoan',     via: 'get'

  match '/support',     to: 'messages#new',             via: 'get'
  match '/support',     to: 'messages#create',          via: 'post'

  

end

app/models/message.rb
class Message
	include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :first_name, :last_name, :email, :content
  
  validates :first_name, :last_name, :email, :content, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  validates :content, length: {maximum: 500}
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET /support and NOT /messages
  def new
    @message = Message.new
  end

  # when user submits contact form, this methid is executed
  # POST /support and NOT /messages
  def create
    @message = Message.new(params[:message])
    if @message.valid?
      # send message via mailer
      MessageMailer.send_message(@message).deliver
      flash[:success] = "Message sent! Thank you for contacting us."
      redirect_to new_message_path
    else
      # if invalid message, then display empty contact form
      #flash[:error] = "Some errors occured. See messages above."
      render :action => 'new'
      #flash.discard
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def apps
  end

  def support
  	#@first_name = params[:firstName]
  	#@last_name = params[:lastName]
  	#@email = params[:emailAddress]
  	#@email_message = params[:emailMessage]

  end

  def houseLoan
  end
  
  def houseBuyRent
  end

  def loanPrepay
  end

  def aprPaydayLoan
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns the full title on a per-page basis
	def full_page_title(page_title)
		base_title = "USRcube"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
	
	# show form input parameters - good debugging function
	def show_form_params
		html = "<div style='border:2px red solid; margin:10px; padding:10px;'>"
		html += '<heading>Form Params</heading><br/>'
		params.each do |key, value|
			html += "#{key}: #{value}<br/>" if (key != 'authenticity_token' && key != 'utf8')
		end
		html += '</div>'
		return html.html_safe
	end

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :notice
        "alert-info"
      when :alert
        "alert-warning"
      when :error
        "alert-danger"
      else
        flash_type.to_s
    end
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_apps_aprpaydayloan.html.erb
<!-- row displaying APRPaydayLoan app-->
<div class="row">

  <div class="col-sm-4 col-sm-offset-2">
  	<p>
     	<%= link_to image_tag("/assets/APRPaydayLoan/aprPaydayLoanIconAppIpad@2x.png", class: "img-responsive"), apps_aprPaydayLoan_path, title:'Payday Loan Interest', rel:'tooltip' %>
      <h4 class="col-sm-offset-0">Payday Loan Interest</h4>
    </p>
	</div>

  <div class="col-sm-6 col-sm-offset-0"> <!-- begin description -->
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Payday Loan Interest</h3>
      </div>
    </div>
      <p>
        <strong>Have you ever wondered what the interest rate is when you take a Payday Loan?</strong>  Then this app calculates the interest rates for different kinds of Payday Loans.  The <strong>Annual Percentage Rate (APR)</strong> and <strong>Effective Annual Rate (EAR)</strong> are calculated for these Payday Loans.  Just enter the loan amount, the amount to pay back, and the number of days to pay back for each Payday Loan.  This app gives you the ability to compare the interest rates of many Payday Loans each with different terms.
      </p>
      <%= link_to apps_aprPaydayLoan_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        View details &raquo;
      <% end %>
      <%= link_to new_message_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        Question or Comment &raquo;
      <% end %>
      <%= link_to "http://appstore.com/paydayloaninterest", :class => "btn btn-default btn-custom", :type => "button" do %>
        Download from App Store &raquo;
      <% end %>
    </p>

  </div> <!-- end description -->

</div> <!-- end APRPaydayLoan app item row -->

app/views/layouts/_apps_buyhouse.html.erb
<!-- row displaying BuyHouse app-->
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
  	<p>
     	<%= link_to image_tag("/assets/HouseBuyRent/AppIconIpadHouseBuyRent@2x.png", class: "img-responsive"), apps_houseBuyRent_path, title:'Buy House Or Rent', rel:'tooltip' %>
      <h4 class="col-sm-offset-1">BuyOrRent?</h4>
    </p>
	</div>
  <div class="col-sm-6 col-sm-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Buy House or Rent</h3>
      </div>
    </div>
 		<p>
    	This app helps you decide whether it is more economical to <strong>buy a house or rent</strong>.
    </p>
    <p>
      The app calculates an <u>estimate</u> of the money, when you buy a house, that does not come back to you AFTER taking into consideration <strong>tax deductions</strong> and <strong>equity accumulation</strong>.  Therefore, if the monthly renting cost is lower than this <u>estimate</u> then it is more economical to rent.  However, if the monthly rent is higher than this <u>estimate</u>, then it is more economical to buy the house.  Since this app makes calculations based on USA tax rules, it is designed for the USA market.
    <p>
      <%= link_to apps_houseBuyRent_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        View details &raquo;
      <% end %>
      <%= link_to new_message_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        Question or Comment &raquo;
      <% end %>
      <%= link_to "http://appstore.com/buyhouseorrent", :class => "btn btn-default btn-custom", :type => "button" do %>
        Download from App Store &raquo;
      <% end %>
    </p>

  </div>
</div> <!-- end BuyHouse app item row -->

app/views/layouts/_apps_fliphouse.html.erb
<!-- row displaying FlipHouse app-->
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
  	<p>
     	<%#= link_to image_tag("/assets/houseLoanIconIpad7@2x.png", class: "img-responsive"), apps_houseLoan_path, title:'Loans for Houses', rel:'tooltip' %>
    </p>
	</div>
  <div class="col-sm-6 col-sm-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Flip House Returns - Coming Soon !!</h3>
      </div>
    </div>
 		<p>
    	This app calculates <strong>Return on Investment</strong> for flipping a house.
    </p>
    <p>
      <%= link_to "#", :class => "btn btn-default btn-custom", :type => "button", :disabled => "disabled" do %>
        View details &raquo;
      <% end %>
      <%= link_to new_message_path, :class => "btn btn-default btn-custom", :type => "button"  do %>
        Question or Comment &raquo;
      <% end %>
      <%= link_to "#", :class => "btn btn-default btn-custom", :type => "button", :disabled => "disabled"  do %>
        Download from App Store &raquo;
      <% end %>
    </p>

  </div>
</div> <!-- end app item row -->

app/views/layouts/_apps_header.html.erb
<h4 align="center">
  Here are our current and upcoming Apps - Please download from the iTunes App Store
</h4>

<!-- add some empty lines -->
<br>

<!-- container is defined in application.html.erb -->

<!-- title row -->
<div class="wall">
	<div class="row">

	  <div class="col-sm-6">
	  	<h2 style="font-size:2.0em"><strong>Apps</strong></h2>
		</div>
	  <div class="col-sm-6">
	  	<h2 style="font-size:2.0em"><strong>Description</strong></h2>
	  </div>

	</div>
</div>  <!-- end title row -->

app/views/layouts/_apps_loanprepay.html.erb
<!-- row displaying LoanPrepay app-->
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
  	<p>
     	<%= link_to image_tag("/assets/LoanPrepay/AppIconIpadLoanPrepay@2x.png", class: "img-responsive"), apps_loanPrepay_path, title:'Prepay Loans', rel:'tooltip' %>
      <h4 class="col-sm-offset-1">PrepayLoan</h4>
    </p>
	</div>
  <div class="col-sm-6 col-sm-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Prepay Loans</h3>
      </div>
    </div>
      <p>
        <strong>Do you want to pay your loans off early and save on interest payments?</strong>  This app will show you how much money you save AND how soon you will clear your loan under various prepaying scenarios.  The prepaying scenarios include making additional payments such as paying extra monthly or paying weekly or calculating the required payments in order to clear the loan in a specified time.
      <p>
        Loan prepayment scenarios can be calculated for many different loans.  Therefore, you can add many loans in this app such as your <strong>house loan</strong>, <strong>car loan</strong>, <strong>personal loan</strong>, or <strong>home equity loan</strong> and evaluate prepayment scenarios for each of them.
      <p>
      </p>
      <%= link_to apps_loanPrepay_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        View details &raquo;
      <% end %>
      <%= link_to new_message_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        Question or Comment &raquo;
      <% end %>
      <%= link_to "http://appstore.com/prepayloans", :class => "btn btn-default btn-custom", :type => "button" do %>
        Download from App Store &raquo;
      <% end %>
    </p>

  </div>
</div> <!-- end LoanPrepay app item row -->

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.usrcube.com/">USRcube</a>
  </small>
  <nav>
    <ul>
      <li><a href="http://www.usrcube.com">Home</a></li>
      <li><%= link_to "Apps",       apps_path %></li>
      <li><%= link_to "Support",    support_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-wrapper">
    <div class="container">

      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

          <div class="navbar-header">
            <!-- button menu when window is made smaller -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <!-- Symbol/logo on left side of navbar -->
            <%= link_to "USRcube", root_path, id: "logo", class: "navbar-brand" %>
          </div>        <!-- end div navbar-header -->

          <!-- Navbar menu on right -->
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">

              <!-- Home menu on navbar -->
              <li><%= link_to (raw("<span class='glyphicon glyphicon-home'></span>"+" Home")), root_path, class: "active" %></li>

              <!-- Apps menu with dropdown on navbar -->
              <li class="dropdown">
                <%= link_to apps_path, :class => "dropdown-toggle", :data => {:toggle => "dropdown"} do %>
                  Apps <b class='caret'></b>
                <% end %>
                <ul class="dropdown-menu">
                  <li><%= link_to "All Apps", apps_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Loan4House", apps_houseLoan_path %></li>
                  <li><%= link_to "BuyOrRent?", apps_houseBuyRent_path %></li>
                  <li><%= link_to "PrepayLoan", apps_loanPrepay_path %></li>
                  <li><%= link_to "PaydayLoanInterest", apps_aprPaydayLoan_path %></li>
                  <li><%= link_to "FlipHouse", apps_path %></li>
                </ul>
              </li>

              <!-- Support menu on navbar -->
              <li><%= link_to "Support", support_path %></li>

            </ul>
          </div>      <!-- end div navbar-collapse collapse -->

        </div>        <!-- end div 2nd container -->
      </div>          <!-- end div navbar navbar-fixed-top navbar-inverse -->

    </div>            <!-- end div first container -->
  </div>              <!-- end div navbar-wrapper -->
</header>

app/views/layouts/_home_apps_list.html.erb
<!-- list of apps on home page -->

<h3 align="left">
  Here are our current Apps - Please download from the iTunes App Store
</h3>

<!-- add some empty lines -->
<br>
<br>

<!-- title row -->
<div class="wall">
	<div class="row">

	  <div class="col-sm-4">
  		<p>
     		<%= link_to image_tag("/assets/houseLoanIconAppIpad@2x.png", class: "img-responsive"), apps_houseLoan_path, title:'Compare House Loans', rel:'tooltip' %>
      	<h4 class="col-sm-offset-1">Loan4House</h4>
    	</p>
		</div>

	  <div class="col-sm-4">
  		<p>
     		<%= link_to image_tag("/assets/HouseBuyRent/AppIconIpadHouseBuyRent@2x.png", class: "img-responsive"), apps_houseBuyRent_path, title:'Buy House Or Rent', rel:'tooltip' %>
      	<h4 class="col-sm-offset-1">BuyOrRent?</h4>
    	</p>
	  </div>

	  <div class="col-sm-4">
  		<p>
    		<%= link_to image_tag("/assets/LoanPrepay/AppIconIpadLoanPrepay@2x.png", class: "img-responsive"), apps_loanPrepay_path, title:'Prepay Loans', rel:'tooltip' %>
      	<h4 class="col-sm-offset-1">PrepayLoan</h4>
    	</p>
	  </div>

    <div class="col-sm-4">
      <p>
        <%= link_to image_tag("/assets/APRPaydayLoan/aprPaydayLoanIconAppIpad@2x.png", class: "img-responsive"), apps_aprPaydayLoan_path, title:'Payday Loan Interest', rel:'tooltip' %>
        <h4 class="col-sm-offset-0">Payday Loan Interest</h4>
      </p>
    </div>

	</div>  <!-- end row -->
</div>  <!-- end wall -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<head>
	  <title><%= full_page_title(yield(:title)) %></title>

	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  
    <%= render 'layouts/shim' %>
	</head>

	<body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
      <%= render 'layouts/flash_messages' %>
      <%= render 'layouts/footer' %>
    </div>
	</body>

</html>

app/views/messages/_contactus_form.html.erb
<%= form_for(@message, html:{class:'form-horizontal'}) do |f| %>
  <% if @message.errors.any? %>
    <div class="panel panel-danger">

      <div class="panel-heading">
        <h2 class="text-danger panel-title">
          <%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:
        </h2>
      </div>

      <div class="panel-body">
        <ul>
          <% @message.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>

    </div>
  <% end %>

    <!--
    <div id="error_explanation">
      <h2 class="text-danger panel panel-danger panel-title panel-heading">
        <%#= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:
      </h2>

      <ul>
        <%# @message.errors.full_messages.each do |msg| %>
          <li><%#= msg %></li>
        <%# end %>
      </ul>
    </div>
    -->

  <form class="form-horizontal" role="form">

    <div class="form-group">
      <%= f.label :first_name, 'First Name', class: "col-sm-2 control-label" %>
      <%= f.text_field :first_name, size:30, placeholder: "Your First Name" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, 'Last Name', class: "col-sm-2 control-label" %>
      <%= f.text_field :last_name, size:30, placeholder: "Your Last Name" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <%= f.text_field :email, size:50, placeholder: "Your email" %>
    </div>

    <div class="form-group">
      <%= f.label :content, class: "col-sm-2 control-label" %>
      <%= f.text_area :content, size: "52x10", placeholder: "Enter your message" %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-10">
        <%= f.submit 'Send Message' %>
      </div>
    </div>
    
  </form>

<% end %>

app/views/messages/_form.html.erb
<%= form_for(@message, html:{class:'form-horizontal'}) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-horizontal" role="form">

    <div class="form-group">
      <%= f.label :first_name, 'First Name', class: "col-sm-2 control-label" %>
      <%= f.text_field :first_name, size:30, placeholder: "Your First Name" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name, 'Last Name', class: "col-sm-2 control-label" %>
      <%= f.text_field :last_name, size:30, placeholder: "Your Last Name" %>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "col-sm-2 control-label" %>
      <%= f.text_field :email, size:30, placeholder: "Your email" %>
    </div>

    <div class="form-group">
      <%= f.label :content, class: "col-sm-2 control-label" %>
      <%= f.text_area :content, size: "32x10", placeholder: "Enter your message" %>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Send Message' %>
      </div>
    </div>
    
  </form>

<% end %>

app/views/messages/new.html.erb
<% provide(:title, 'Support') %>

<h1>Support</h1>
<!--
<p>
  This is the Support page for 
  <a href="http://www.usrcube.com/">USRcube</a>
  company.
</p>
-->
<h1><small>Contact Us</h1>

<%= render 'contactus_form' %>

app/views/static_pages/apps.html.erb
<% provide(:title, 'Apps') %>

<h1>Apps</h1>

<%= render 'layouts/apps_header' %>

<!-- rows displaying apps-->
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
  	<p>
     	<%= link_to image_tag("/assets/houseLoanIconAppIpad@2x.png", class: "img-responsive"), apps_houseLoan_path, title:'Compare House Loans', rel:'tooltip' %>
      <h4 class="col-sm-offset-1">Loan4House</h4>
    </p>
	</div>
  <div class="col-sm-6 col-sm-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Compare House Loans</h3>
      </div>
    </div>
 		<p>
    	Calculate and compare house loan payments from <strong>Fixed Rate Mortgage</strong> and <strong>Adjustable Rate Mortgage</strong>.  This app helps you to project monthly loan payments for either the Fixed Loan Mortgage or the Adjustable Rate Mortgage or both.  The <strong>TOTAL of All Payments</strong> and <strong>TOTAL of All Interest Paid</strong> to the lender are also evaluated.
    </p>
    <p>
      Payments can be calculated for many houses each with different types of loans.  All loan data for different houses can be saved.  Therefore, there is no need to recreate the loans for different houses.
    </p>
    <p>
      <%= link_to apps_houseLoan_path, :class => "btn btn-default btn-custom", :type => "button" do %>
        View details &raquo;
      <% end %>
      <%= link_to new_message_path, :class => "btn btn-default btn-custom", :type => "button"  do %>
        Question or Comment &raquo;
      <% end %>
      <%= link_to "http://appstore.com/comparehouseloans", :class => "btn btn-default btn-custom", :type => "button"  do %>
        Download from App Store &raquo;
      <% end %>
    </p>
  </div>
</div> <!-- end app item row -->

<br/>
<br/>

<!-- row displaying BuyHouse app-->
<%= render 'layouts/apps_buyhouse' %>

<br/>
<br/>

<!-- row displaying LoanPrepay app-->
<%= render 'layouts/apps_loanprepay' %>

<br/>
<br/>

<!-- row displaying APRPaydayLoan app-->
<%= render 'layouts/apps_aprpaydayloan' %>

<br/>
<br/>

<!-- row displaying FlipHouse app-->
<%= render 'layouts/apps_fliphouse' %>

app/views/static_pages/aprPaydayLoan.html.erb
<% provide(:title, 'Payday Loan Interest') %>

<h1>Payday Loan Interest</h1>

<!-- display app info-->
<div class="row">

  <div class="col-sm-4 col-sm-offset-2">
    <p>
      <%= link_to image_tag("/assets/APRPaydayLoan/aprPaydayLoanIconAppIpad@2x.png", class: "img-responsive"), apps_aprPaydayLoan_path, title:'Payday Loan Interest', rel:'tooltip' %>
    </p>
    <p>
      <%= link_to "http://appstore.com/paydayloaninterest", :class => "btn btn-default" do %>
        Download from App Store &raquo;
      <% end %>
    </p>
  </div>

  <div class="col-sm-6 col-sm-offset-0">
    <div class="panel panel-info">
      <div class="panel-heading"
        <h3 class="text-info panel-title">Payday Loan Interest</h3>
      </div>
    </div>
    <p>
        <strong>Have you ever wondered what the interest rate is when you take a Payday Loan?</strong>  Then this app calculates the interest rates for different kinds of Payday Loans.  The <strong>Annual Percentage Rate (APR)</strong> and <strong>Effective Annual Rate (EAR)</strong> are calculated for these Payday Loans.  Just enter the loan amount, the amount to pay back, and the number of days to pay back for each Payday Loan.  This app gives you the ability to compare the interest rates of many Payday Loans each with different terms.
    </p>
  </div>
</div> <!-- end display app info -->


<!-- Carousel to view the process of creating Payday Loans and viewing results
================================================== -->
<br/>
<br/>
<h3 class="col-sm-offset-1">
  To view the interest rates for a Payday Loan, please follow the steps outlined below:
</h3>
<br/>
<br/>

<div id="paydayloanCarousel" class="carousel slide col-sm-offset-1" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#paydayloanCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#paydayloanCarousel" data-slide-to="1"></li>
    <li data-target="#paydayloanCarousel" data-slide-to="2"></li>
    <li data-target="#paydayloanCarousel" data-slide-to="3"></li>
  </ol>

  <div class="carousel-inner">

    <!-- First carousel item -->
    <div class="item active">
      <%= tag("img", src: "/assets/APRPaydayLoan/1appOverviewIphone5APRPaydayLoanEnCreateLoans.png", class: "img-responsive", alt: "First slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Payday Loan</h1>
          <p>Tap on  +  to create a Payday Loan</p>
        </div>
      </div>
    </div>

    <!-- Second carousel item -->
    <div class="item">
      <%= tag("img", src: "/assets/APRPaydayLoan/2appOverviewIphone5APRPaydayLoanEnInputLoan.png", class: "img-responsive", alt: "Second slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1>Loan Information</h1>
          <p>Enter the Payday Loan details.</p>
        </div>
      </div>
    </div>

    <!-- Third carousel item -->
    <div class="item">
      <%= tag("img", src: "/assets/APRPaydayLoan/4appOverviewIphone5APRPaydayLoanEnResultInterestRates.png", class: "img-responsive", alt: "Third slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1 class="cyan-color">Interest Rates</h1>
          <p class="cyan-color">Calculate Interest Rates for the Payday Loan by tapping the "Calculate" button.</p>
        </div>
      </div>
    </div>

    <!-- Fourth carousel item -->
    <div class="item">
      <%= tag("img", src: "/assets/APRPaydayLoan/3appOverviewIphone5APRPaydayLoanEnHowTo.png", class: "img-responsive", alt: "Fourth slide") %>
      <div class="container">
        <div class="carousel-caption">
          <h1 class="text-info cyan-color">How To Use</h1>
          <p class="cyan-color">Create many Payday Loans to compare. Select any to view results.</p>
        </div>
      </div>
    </div>

  </div>   <!-- end carousel inner -->

  <!-- carousel navigation -->
  <a class="left carousel-control" href="#paydayloanCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
  <a class="right carousel-control" href="#paydayloanCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>

</div><!-- /. end paydayloanCarousel to create Payday Loan and view results -->

app/views/static_pages/home.html.erb
<!-- home page title and brief description-->
<div class="center jumbotron">
	<h1>USRcube</h1>
	<br/>
	<h2>
	  USRcube develops apps for mobile phones.  The current and upcoming apps are described in the
	  <%= link_to "Apps", apps_path %>
	  page.  We are also available for hire to develop apps.  Please contact us on the
	  <%= link_to "Support", support_path %>
	  page.
	</h2>
</div>

<!-- display list of apps on home page -->
<%= render 'layouts/home_apps_list' %>

app/views/static_pages/support.html.erb
<%# provide(:title, 'Support') %>

<!--
<h1>Support</h1>
<p>
  This is the Support page for 
  <a href="http://www.usrcube.com/">USRcube</a>
  company.
</p>

<%#= form_tag do %>
	<%#= label_tag  'firstName', "First Name" %>
	<%#= text_field_tag 'firstName', @first_name, placeholder: 'Enter your First Name' %><br/>
	<%#= label_tag 'lastName', "Last Name" %>
	<%#= text_field_tag 'lastName', @last_name, placeholder: 'Enter your Last Name' %><br/>
	<%#= label_tag 'emailAddress', "Email" %>
	<%#= email_field_tag 'emailAddress', @email, placeholder: 'Enter your email address' %><br/>
	<%#= label_tag 'emailMessage', "Message" %>
	<%#= text_area_tag 'emailMessage', @email_message, placeholder: 'Please enter your message here', size: "50x10" %><br/>
	<%#= submit_tag "Send Message" %>
<%# end %>
-->